development: 
   adapter: sqlite3
   database: db/development.sqlite3
   pool: 5
   timeout: 5000

# Read the database configuration from the system odbc
# configuration.
#
<% system_odbc_ini_file = '/var/lib/.odbc.ini' %>
<% if File.exists?(system_odbc_ini_file) %>
<% system_odbc_configuration = IniFile.load(system_odbc_ini_file) %>
<% if !system_odbc_configuration['gemeinschaft']['DATABASE'].blank? && !system_odbc_configuration['gemeinschaft']['USER'].blank? %>
production: 
   adapter: mysql2 
   encoding: utf8 
   database: <%= system_odbc_configuration['gemeinschaft']['DATABASE'] %>
   pool: 10 
   username: <%= system_odbc_configuration['gemeinschaft']['USER'] %>
   password: <%= system_odbc_configuration['gemeinschaft']['PASSWORD'] %>
   socket: /var/run/mysqld/mysqld.sock 
   reconnect: true
<% else %>
production: 
   adapter: mysql2 
   encoding: utf8 
   database: gemeinschaft 
   pool: 10 
   username: gemeinschaft 
   password: gemeinschaft 
   socket: /var/run/mysqld/mysqld.sock 
   reconnect: true
<% end %>
<% end %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

test:
   adapter: sqlite3
   database: db/test.sqlite3
   pool: 5
   timeout: 5000